variable "creation_token" {
  description = "Optional) A unique name (a maximum of 64 characters are allowed) used as reference when creating the Elastic File System to ensure idempotent file system creation. By default generated by Terraform. See Elastic File System user guide for more information."
  type = number
  default = null
}

variable "name" {
  type        = string
  description = "(Required) The reference_name of your file system. Also, used in tags."
}

variable "subnets" {
  type        = list(string)
  description = "(Required) A list of subnet ids where mount targets will be."
}

variable "vpc_id" {
  type        = string
  description = "(Required) The VPC ID where NFS security groups will be."
}

variable "encrypted" {
  description = "(Optional) If true, the disk will be encrypted"
  default     = false
  type        = bool
}

variable "kms_key_id" {
  type        = string
  description = "The ARN of the key that you wish to use if encrypting at rest. If not supplied, uses service managed encryption. Can be specified only if `encrypted = true`"
  default     = null
}

variable "performance_mode" {
  description = "(Optional) The file system performance mode. Can be either generalPurpose or maxIO"
  type = string
  default = "generalPurpose"
}

variable "provisioned_throughput_in_mibps" {
  description = "(Optional) The throughput, measured in MiB/s, that you want to provision for the file system. Only applicable with throughput_mode set to provisioned"
  type = number
  default = null
}

variable "tags" {
  description = "A mapping of tags to apply to resources"
  type        = map(string)
  default     = {}
}

variable "throughput_mode" {
  description = "(Optional) Throughput mode for the file system. Defaults to bursting. Valid values: bursting, provisioned, or elastic. When using provisioned, also set provisioned_throughput_in_mibps"
  type = string
  default = "bursting"
}

variable "transition_to_ia" {
  description = "(Optional) Indicates how long it takes to transition files to the IA storage class. Valid values: AFTER_1_DAY, AFTER_7_DAYS, AFTER_14_DAYS, AFTER_30_DAYS, AFTER_60_DAYS, or AFTER_90_DAYS"
  type = string
  default = null
}

variable "transition_to_primary_storage_class" {
  description = " (Optional) Describes the policy used to transition a file from infequent access storage to primary storage. Valid values: AFTER_1_ACCESS"
  type = string
  default = null
}
